
# General (previously Qbi.runner options)
#data_dir: null
output_dir: logs/qMRI_processes
# no_audit: True # -- this is a madym option

# Inputs
dce_path: dce/dce_dyn_echo1
T1_path: madym_output/T1_VFA/T1.nii.gz

dce_im_ext: .nii.gz
dce_meta_ext: .json
#roi_path: null

# Parameters
dce_limits: [2, 9, 11, 15] 
relax_coeff: 0
average_fun: median
alternative: less
equal_var: True

# Output
maps_dir: DCE_output_maps




